In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

DATASET_PATH = "dataset"

In [2]:
sets = pd.read_csv(DATASET_PATH + "/sets.csv")

themes = pd.read_csv(DATASET_PATH + "/themes.csv")
themes.rename(columns = {'id':'theme_id'}, inplace = True)

sets = sets.merge(themes, on='theme_id', how='left')
sets.rename(columns = {'name_x':'set_name','name_y':'theme_name'}, inplace = True)

sets.set_num.nunique()

11673

In [3]:
inv = pd.read_csv(DATASET_PATH + "/inventories.csv")
inv.set_num.nunique()

11670

In [7]:
inv = inv.merge(sets, on='set_num', how='left')
inv.set_num.nunique()

11670

In [8]:
inv_part = pd.read_csv(DATASET_PATH + "/inventory_parts.csv")

colors = pd.read_csv(DATASET_PATH + "/colors.csv")
colors.rename(columns = {'id':'color_id'}, inplace = True)

inv_part = inv_part.merge(colors, on='color_id', how='left')
inv_part.rename(columns = {'inventory_id':'id'}, inplace = True)
inv_part.shape

(580251, 8)

In [15]:
df = inv_part.merge(inv, on='id', how='left')
print('Cantidad de sets: ',df.set_num.nunique())
df.head()

Cantidad de sets:  10713

,id,part_num,color_id,quantity,is_spare,name,rgb,is_trans,version,set_num,set_name,year,theme_id,num_parts,theme_name,parent_id
0,1,48379c01,72,1,f,Dark Bluish Gray,6C6E68,f,1,7922-1,McDonald's Sports Set Number 6 - Orange Vest S...,2004,460,4,Gravity Games,458.0
1,1,48395,7,1,f,Light Gray,9BA19D,f,1,7922-1,McDonald's Sports Set Number 6 - Orange Vest S...,2004,460,4,Gravity Games,458.0
2,1,mcsport6,25,1,f,Orange,FE8A18,f,1,7922-1,McDonald's Sports Set Number 6 - Orange Vest S...,2004,460,4,Gravity Games,458.0
3,1,paddle,0,1,f,Black,05131D,f,1,7922-1,McDonald's Sports Set Number 6 - Orange Vest S...,2004,460,4,Gravity Games,458.0
4,3,11816pr0005,78,1,f,Light Flesh,F6D7B3,f,1,3931-1,Emma's Splash Pool,2012,494,43,Friends,NaN

In [57]:
df_ = df.drop(['parent_id', 'theme_id', 'year', 'version', 'is_trans', 'is_spare',  'quantity',
                   'color_id',  'part_num',  'id'], axis = 'columns')
df_

,name,rgb,set_num,set_name,num_parts,theme_name
0,Dark Bluish Gray,6C6E68,7922-1,McDonald's Sports Set Number 6 - Orange Vest S...,4,Gravity Games
1,Light Gray,9BA19D,7922-1,McDonald's Sports Set Number 6 - Orange Vest S...,4,Gravity Games
2,Orange,FE8A18,7922-1,McDonald's Sports Set Number 6 - Orange Vest S...,4,Gravity Games
3,Black,05131D,7922-1,McDonald's Sports Set Number 6 - Orange Vest S...,4,Gravity Games
4,Light Flesh,F6D7B3,3931-1,Emma's Splash Pool,43,Friends
...,...,...,...,...,...,...
580246,Black,05131D,75090-2,Ezra's Speeder Bike,253,Star Wars Rebels
580247,Light Bluish Gray,A0A5A9,75090-2,Ezra's Speeder Bike,253,Star Wars Rebels
580248,White,FFFFFF,75090-2,Ezra's Speeder Bike,253,Star Wars Rebels
580249,Black,05131D,75090-2,Ezra's Speeder Bike,253,Star Wars Rebels
580250,Dark Bluish Gray,6C6E68,75090-2,Ezra's Speeder Bike,253,Star Wars Rebels

In [58]:
df_.set_num.nunique()

10713

In [59]:
count_colors = df_.rgb.value_counts().to_dict()
sum(count_colors.values())

580251

In [60]:
df_g=df_.groupby('set_num',as_index=False)['rgb'].nunique()
print('Cantidad máxima de colores en set:', df_g.rgb.max())

Cantidad máxima de colores en set: 43

In [66]:
df_d=df_.drop_duplicates(ignore_index = True)
df_d.shape
df_d

,name,rgb,set_num,set_name,num_parts,theme_name
0,Dark Bluish Gray,6C6E68,7922-1,McDonald's Sports Set Number 6 - Orange Vest S...,4,Gravity Games
1,Light Gray,9BA19D,7922-1,McDonald's Sports Set Number 6 - Orange Vest S...,4,Gravity Games
2,Orange,FE8A18,7922-1,McDonald's Sports Set Number 6 - Orange Vest S...,4,Gravity Games
3,Black,05131D,7922-1,McDonald's Sports Set Number 6 - Orange Vest S...,4,Gravity Games
4,Light Flesh,F6D7B3,3931-1,Emma's Splash Pool,43,Friends
...,...,...,...,...,...,...
94317,Flat Silver,898788,75090-2,Ezra's Speeder Bike,253,Star Wars Rebels
94318,Trans-Red,C91A09,75090-2,Ezra's Speeder Bike,253,Star Wars Rebels
94319,Trans-Bright Green,D9E4A7,75090-2,Ezra's Speeder Bike,253,Star Wars Rebels
94320,Dark Orange,A95500,75090-2,Ezra's Speeder Bike,253,Star Wars Rebels
94321,Dark Tan,958A73,75090-2,Ezra's Speeder Bike,253,Star Wars Rebels

In [65]:
df_d.pivot(index= 'set_num', columns = 'rgb')#, values=None)

ValueError: Index contains duplicate entries, cannot reshape